### ISSUE TITLE
User popout addon are broken.

### ISSUE THREAD

**Issue by Mef45** [Snow-Pyon/BDStuff#1]
Since discord stuff released new features, userpopouts addon looks really bad.
Can you fix it please?
![image](https://user-images.githubusercontent.com/26562037/33421181-1ef65616-d5d3-11e7-8c3e-4b82d60971f9.png)

**Comment by Mef45** [comment]
Without any plugins it's also look bad
![image](https://user-images.githubusercontent.com/26562037/33421410-b9a0f360-d5d3-11e7-9c62-58a7f1c6eff3.png)

**Comment by zerebos** [comment]
Beautiful
